### ISSUE TITLE
python 3 update

### ISSUE THREAD

**Issue by paul0008** [jpaille/streamripper.py#1]

**Comment by paul0008** [comment]
Hi,
I try to run streamripper with python3 and fix errors up to a level I am capable of.
Looks like I'm nearly there...
Can you please post a few tips how to work arround these errors ?

~/streamripper$ python3 streamripper.py https://stream.praypraypray.net:9006/stream -d ./
Connecting...
Traceback (most recent call last):
  File "/home/j/streamripper/streamripper.py", line 69, in <module>
    stream = requests.get(args.url, stream=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "/home/j/streamripper/.venv/lib/python3.11/site-packages/requests/utils.py", line 1049, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Header part (1) from ('Icy-MetaData', 1) must be of type str or bytes, not <class 'int'>

**Comment by paul0008** [comment]
Hi,
I try to run streamripper with python 3 and fix error up to a level I'm capable of.
Can you please post a few tips how to work arround these errors ?


~/streamripper$ python3 streamripper.py https://stream.praypraypray.net:9006/stream -d ./
Connecting...
Traceback (most recent call last):
  File "/home/paul0008/streamripper/streamripper.py", line 69, in <module>
    stream = requests.get(args.url, stream=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "/home/paul0008/streamripper/.venv/lib/python3.11/site-packages/requests/utils.py", line 1049, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Header part (1) from ('Icy-MetaData', 1) must be of type str or bytes, not <class 'int'>
